language: node_js
node_js:
- '8'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: BTEQavkGV9RXCgX797/I3Spy1mrBYDQxow9xIQZ4+Ismajec1MufEamrtcYcNLl9/h9CYgmYNSbi0HLjTLv6KrStwvVaJdS0ta2EUKNmR6lNpUSlQfITd1Qd2d0+wE0r6dKGQYlJpZESVKk4FEvWWFv6GTWxv61UrB197AAkuUUmndoBylSoomzjI1aFLqmnU51TR0e4AU8QD7eBTOiVFAkvLlV3+xC8tZFCwSR+2+RPGWXhCwjNrJMMm0Zw695ivpvZFjcYNiF0Hv82YEmv592v7Y7fW/kpQCQ7KjoTL5UNATZBiefHaP/4jr/qrchEIip1BAZ9mIKoEsoy+v9Kb7oYL5bPC0JDuLNJDxlNGicuOpVeberGCj7/OVhwr6IqFAPLgtos9v21bwzcpVf5mM0p75FLFpDow6w+SF4V0lrWJXxAac0lWEXsMvImi8NsjhNVG6hZ6xjhCfTN3iQ87bCmZCPq1QMLUf+9F9G1tOCZHw7XnoGqtzHXby4/4DszgSQ0i24a15DwVvPH8+7dKyl8x8R0EYtE42P6gEc1gzD4iO9wNPRdqqe08SgcIaf5qQ+ZMe82BmCCuqGTMPJvVIgcu1isYIQ/rshgvUHyaFT3Lz1soWxlu6UpsikklZFhfn84yU7CLOsvcGkmWvNvybUGrQCubb91U+ycFqaO7ac=
    on_success: always
    on_failure: always
script:
- bash .travis.build.sh
