FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG KRAWLER_BRANCH
ENV KRAWLER_BRANCH=$KRAWLER_BRANCH

RUN git clone https://github.com/kalisio/krawler.git -b $KRAWLER_BRANCH --single-branch && cd krawler && yarn install && cd ..

COPY jobfile-stations.js .

CMD node ./krawler --cron "0 0 0 * * *" jobfile-stations.js

