FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ENV DEBUG=

RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV NODE_PATH=/home/node/.npm-global/lib/node_modules

RUN npm install -g @kalisio/krawler@0.7.0 --unsafe
RUN npm install -g lodash@4.17.10

COPY jobfile-observations.js .

CMD krawler --cron "0 10 * * * *" jobfile-observations.js
